name: CI Qt CMake (Windows) and PlatformIO

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  # Job for building the C++ Qt 5 client project on Windows
  client-build-windows:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install CMake
      - name: Install CMake
        uses: lukka/get-cmake@v3.21.2

      # Step 3: Install Qt 5 and MinGW on Windows
      - name: Install Qt 5 and MinGW
        run: |
          choco install qt5-default
          choco install mingw
          echo "Qt 5 and MinGW installed"

      # Step 4: Set up MinGW in the system path
      - name: Add MinGW to PATH
        run: |
          echo "C:\Program Files\mingw-w64\mingw64\bin" >> $env:GITHUB_PATH
        shell: pwsh

      # Step 5: Create build directory
      - name: Create build directory
        run: mkdir build
        working-directory: client

      # Step 6: Configure project using CMake with MinGW
      - name: Configure with CMake for MinGW
        run: cmake -G "MinGW Makefiles" ..
        working-directory: client/build

      # Step 7: Build the project using MinGW
      - name: Build client app
        run: cmake --build .
        working-directory: client/build

      # Step 8: Use windeployqt to gather Qt DLLs for MinGW
      - name: Deploy Qt DLLs using windeployqt (MinGW)
        run: |
          C:\Qt\5.x.x\mingw81_64\bin\windeployqt.exe --release --compiler-runtime client/build/my_client.exe
        shell: cmd
        working-directory: client/build

      # Step 9: Run tests (assuming tests are defined in CMakeLists.txt)
      - name: Run tests
        run: ctest --output-on-failure --config Release
        working-directory: client/build

      # Step 10: Upload client build artifacts, including DLLs
      - name: Upload Client build artifact
        uses: actions/upload-artifact@v4
        with:
          name: client-build-windows
          path: client/build/

  # Job for building the PlatformIO server project
  server-build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install PlatformIO
      - name: Install PlatformIO
        run: |
          python3 -m pip install -U platformio

      # Step 3: Build PlatformIO project
      - name: Build PlatformIO project
        run: pio run
        working-directory: server

      # Step 4: Upload PlatformIO build artifacts
      - name: Upload Server build artifact
        uses: actions/upload-artifact@v4
        with:
          name: server-build
          path: server/.pio/build/*
