name: CI Qt CMake (Windows) and PlatformIO

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  # Job for building the C++ Qt 5 client project on Windows
  client-build-windows:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install CMake
      - name: Install CMake
        uses: lukka/get-cmake@v3.21.2

      # Step 3: Install Qt 5 on Windows
      - name: Install Qt 5
        run: |
          choco install qt5-default
          echo "Qt 5 installed"

      # Step 4: Create build directory
      - name: Create build directory
        run: mkdir build
        working-directory: client

      # Step 5: Configure project using CMake
      - name: Configure with CMake
        run: cmake -G "MinGW Makefiles" ..
        working-directory: client/build

      # Step 6: Build the project
      - name: Build client app
        run: cmake --build .
        working-directory: client/build

      # Step 7: Upload client build artifacts
      - name: Upload Client build artifact
        uses: actions/upload-artifact@v4
        with:
          name: client-build-windows
          path: client/build/

  # Job for building the PlatformIO server project
  server-build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install PlatformIO
      - name: Install PlatformIO
        run: |
          python3 -m pip install -U platformio

      # Step 3: Build PlatformIO project
      - name: Build PlatformIO project
        run: pio run
        working-directory: server

      # Step 4: Upload PlatformIO build artifacts
      - name: Upload Server build artifact
        uses: actions/upload-artifact@v4
        with:
          name: server-build
          path: server/.pio/build/*
